SELECT * FROM ORDERS

1) Arrange the ‘Orders’ dataset in decreasing order of amount

SELECT * FROM ORDERS ORDER BY AMOUNT DESC

2)Create a table with the name ‘Employee_details1’ consistingof thesecolumns: ‘Emp_id’, ‘Emp_name’, ‘Emp_salary’. Create another tablewiththe name ‘Employee_details2’ consisting of the same columns asthefirst
table.
  CREATE TABLE EMPLOYEE_DETAILS1(EMP_ID INT,EMP_NAME VARCHAR(30),EMP_SALARY INT)
  CREATE TABLE EMPLOYEE_DETAILS2(EMP_ID INT,EMP_NAME VARCHAR(30),EMP_SALARY INT)

  INSERT INTO EMPLOYEE_DETAILS1(EMP_ID,EMP_NAME,EMP_SALARY) VALUES
  (1,'SRUTHI',200000),
  (2,'KANNA',30000),
  (3,'RADHA',10200);

  INSERT INTO EMPLOYEE_DETAILS2(EMP_ID,EMP_NAME,EMP_SALARY) VALUES
  (1,'SOMU',20500),
  (5,'KUSHI',30000),
  (3,'RAM',31020);


 3)Apply the UNION operator on these two tables
 SELECT * FROM EMPLOYEE_DETAILS1 UNION SELECT * FROM EMPLOYEE_DETAILS2

 4) Apply the INTERSECT operator on these two tables
 SELECT EMP_ID,EMP_NAME,EMP_SALARY FROM EMPLOYEE_DETAILS1 INTERSECT SELECT EMP_ID,EMP_NAME,EMP_SALARY FROM EMPLOYEE_DETAILS2

 5)Apply the EXCEPT operator on these two tables
 SELECT EMP_ID,EMP_NAME,EMP_SALARY FROM EMPLOYEE_DETAILS1 EXCEPT SELECT EMP_ID,EMP_NAME,EMP_SALARY FROM EMPLOYEE_DETAILS2